refactor(restclient): do not require input argument on fully optional interface
skyleague/therefore pull request #15
Opened 2022-08-24 11:47 UTC by pevisscher

2022-08-24 11:48 UTC, pevisscher commented
Current dependencies on/for this PR:
* main
  * **PR #13** <a href="https://app.graphite.dev/github/pr/skyleague/therefore/13" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #14** <a href="https://app.graphite.dev/github/pr/skyleague/therefore/14" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #15** <a href="https://app.graphite.dev/github/pr/skyleague/therefore/15" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/skyleague/therefore/15?utm_source=stack-comment).

2022-08-25 08:30 UTC, MickVanDuijn requested changes
See inline comments

2022-08-25 08:30 UTC, MickVanDuijn commented on src/lib/primitives/restclient/restclient.ts
> +                    const hasRequiredQueryArguments = queryArguments.length > 0
```suggestion
                    const hasRequiredQueryArguments = queryArguments?.some((q) => q.required === true)
```

2022-08-25 08:53 UTC, MickVanDuijn approved these changes

2022-08-25 08:55 UTC, pevisscher commented
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/skyleague/therefore/15?utm_source=stack-comment).
<!-- SHOW_IN_GRAPHITE_UI -->

Job Reference: 3k1UzKXl5ZWLtCzZn7QI

2022-08-25 08:58 UTC, merged