feat(http): add header and query validators
skyleague/therefore pull request #31
Opened 2022-09-06 20:28 UTC by pevisscher

2022-09-06 20:29 UTC, pevisscher commented
Current dependencies on/for this PR:
* main
  * **PR #31** <a href="https://app.graphite.dev/github/pr/skyleague/therefore/31" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈
    * **PR #32** <a href="https://app.graphite.dev/github/pr/skyleague/therefore/32" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/skyleague/therefore/31?utm_source=stack-comment).

2022-09-07 05:41 UTC, MickVanDuijn requested changes
See inline comments

2022-09-07 05:41 UTC, MickVanDuijn commented on src/lib/primitives/jsonschema/jsonschema.ts
> +        const additionalProperties = node.additionalProperties === false ? undefined : context.strict ? undefined : true
this feels like another change snuck into this PR

2022-09-07 06:24 UTC, MickVanDuijn approved these changes

2022-09-07 07:52 UTC, pevisscher commented
**Graphite Merge Job**

Current status: 🔄 Waiting for checks to pass

This pull request is currently waiting for CI and mergeability checks to pass before being merged.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/skyleague/therefore/31?utm_source=stack-comment).
<!-- SHOW_IN_GRAPHITE_UI -->

Job Reference: 9BzgHsfDernqvMzHCN2o

2022-09-07 07:58 UTC, pevisscher commented
**Graphite Merge Job**

Current status: 🔄 Waiting for checks to pass

This pull request is currently waiting for CI and mergeability checks to pass before being merged.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/skyleague/therefore/31?utm_source=stack-comment).
<!-- SHOW_IN_GRAPHITE_UI -->

Job Reference: 4q7XSmmn1AMhDgyvtGlo

2022-09-07 07:58 UTC, merged